# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: windows-2019

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: Install .NET Core SDK
  inputs:
    packageType: 'sdk'
    useGlobalJson: true
    workingDirectory: 'SportsStore'

- script: dotnet restore src\SportsStore.csproj
  displayName: 'Restore'
  workingDirectory: 'SportsStore'

- script: dotnet build --no-restore --configuration $(buildConfiguration) src\SportsStore.csproj
  displayName: 'Build project'
  workingDirectory: 'SportsStore'

- script: |
    dotnet test --configuration $(buildConfiguration) test\SportsStore.IntegrationTests\SportsStore.IntegrationTests.csproj
    dotnet test --configuration $(buildConfiguration) test\SportsStore.Tests\SportsStore.Tests.csproj
  displayName: 'Build and run test projects'
  workingDirectory: 'SportsStore'
